config/routes.rb
Rails.application.routes.draw do
  resources :products
  '''
  Prefix         Verb     URI Pattern                   Controller#Action
  products       GET      /products(.:format)           products#index
                 POST     /products(.:format)           products#create
  new_product    GET      /products/new(.:format)       products#new
  edit_product   GET      /products/:id/edit(.:format)  products#edit
  product        GET      /products/:id(.:format)       products#show
                 PATCH    /products/:id(.:format)       products#update
                 PUT      /products/:id(.:format)       products#update
                 DELETE   /products/:id(.:format)       products#destroy
  '''
  post '/products/search' =>"products#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/top'=>"home#top"
  get '/detail'=>"home#detail"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    #mount_uploader :picture, PictureUploader
    validates :item, {presence: true, length: {maximum: 100}}
    validates :content, {presence: true, length: {maximum: 500}}
    validates :shop, presence: true
    validates :price, presence: true
    #validates :picture, presence: true

    def self.search(search)
        if search
            Product.where(["item Like or shop Like or price Like?","%#{search}%"])
        else
            Product.all   #どうしてerrorの場合はすべての情報をProduct.allでreadする必要がある？？
            respond_to do |format|
                format.html { redirect_to :index, notice: '正しい検索項目を入力してください' }
                format.json { render json: @product.errors, status: :unprocessable_entity }
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top   #top画面を表示
  end
  def detail
    #存在意義が/Prpducts/indexとほほ同じなので消してもいいかと考えていましたが、店舗の概念を追加するときに
    #さらに入れ子の構造になったりするかと思いつつ残しています。
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  #登録された商品情報一覧と他のpageへのリンク
  def index
    @products = Product.all
  end
  
  #検索結果一覧表示
  def search
    @products = Product.search(params[:search])
    respond_to do |format|
      format.html { redirect_to @product, notice: '検索結果一覧' }
      format.json { render :show, status: :done, location: @product }
    end
  end
  

  # GET /products/1
  # GET /products/1.json
  #個々の商品詳細ページ表示
  def show
    #すでにset_productで@Productの情報取得
  end

  #read new input info→form（→create)
  # GET /products/new
  def new
    @product = Product.new
  end
  
  #read new info to edit//title,or content,or shop→form（→uodate)
  # GET /products/1/edit
  def edit
    #すでにset_productで@Productの情報取得
  end


  #form→
  # POST /products
  # POST /products.json
  def create
    @product = Product.new
    respond_to do |format|
      if @product.save!
        format.html { redirect_to @product, notice: '商品登録が完了しました' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  #form→
  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|#responseの形式で分岐(html/json)
      #Progateのチュートリアルで画像投稿練習をしたときのものです。
      #この時はすでにPublicフォルダに画像があることが前提でした
      '''if params[:image]
        @product.image_name = "#{@product.id}.jpg"
        image = params[:image]
        File.binwrite("public/product_images/#{@product.image_name}", image.read)
      end
      '''

      if @product.update(product_params.permit(:item,:content,:price,:picture)) #:picture_cache, :remove_picture))
        format.html { redirect_to @product, notice: '商品情報が変更されました' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: '商品情報が削除されました' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:item, :content, :shop, :price, :picture, :picture_cache, :remove_picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/detail.html.erb
<div class="detail-main">
  <h2>ProductAppとは</h2>
  <p>
  </p>
  <p>
    あらゆる商品情報取り扱いサービスです。
    各商品について、「商品画像」「商品タイトル」「商品説明」「値段」の登録、検索、変更、削除が簡単にできます。
  </p>
  <img class="detail-img" src="9da718926e0b0a668f618f5e291cbba1_m.jpg",>
</div>

app/views/home/top.html.erb
<div class="main top-main">
  <div class="top-message">
    <h2>あらゆる商品情報管理はすべておまかせ！</h2>
    <p>まずは便利さを実感してみよう</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webinterface</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">

    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>

  <!--上記のリンクはRails girlをみて追加しましたが、既存のviewとの調整がまだ勉強不足でできておりません。
  また, headerもすべて横に並列にしたいのですがまだです-->
  <!--もう一点は入力formが今上記の追加headerによって隠されてしまいます、、のでその辺をhtmlしたあとに直していきます-->
    <body>
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/top">The Products app</a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/products">商品一覧</a></li>
            </ul>
          </div>
            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/detail">What is Products App？</a></li>
              </ul>
            </div>
            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/products/new">新規商品登録</a></li>
              </ul>
            </div>
        </div>
      </nav>
    </header>

    <!--
    <header>
      <div class="header-logo">
        <%= link_to("Products App", "/") %>
      </div>
      <ul class="header-menus">
        <li>
          <%= link_to("What is Products App?","/detail") %>
        </li>
        <li>
          <%= link_to("商品一覧", "/products") %>
        </li>
        <li>
          <%= link_to("新規商品登録", "/products/new") %>
        </li>
        <!--<li>
          <%= link_to("商品検索", "/users/index") %>
        </li>
        <li>
          <%= link_to("新規登録", "/signup") %>
        </li>
      </ul>
    </header>-->
    
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>

</html>

app/views/products/_form.html.erb
<!#form_withの使い方
#https://techracho.bpsinc.jp/hachi8833/2017_05_01/39502/
#scaffoldによる自動生成
https://qiita.com/kakiuchis/items/9ab8dc212ed5c57a2ddd
>

<!--application.htmlの方のheaderが優先されてしまって上の方の入力画面が見えなくなってしまっています。。-->

<%= form_with(model: product, local: true, html: {multipart: true}) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!--form_tagとform_withを分けて書くのかいまいちよくわかりません。。上記form_with内のerror表示はデフォルトでありました-->
<!--createを呼び出すものが何もなく追加, ですがserverで登録するをおしてもcreateにいってないようです、おそらくerrorから
画像の読み込みができていないように思います。-->
    <%= form_tag('/products/create', method: :post, multipart: true) do %>
    <div class="field">
      <%= form.label :'商品タイトル' %>
      <%= form.text_field :item, id: :product_title%>
    </div>

    <div class="field">
      <%= form.label :'商品説明' %>
      <%= form.text_area :content %>
    </div>

    <div class="field">
      <%= form.label :'店舗名' %>
      <%= form.text_field :shop %>
    </div>


    <div class="field">
        <% if @product.picture? %>
          <div class="thumbnail">
            <%= image_tag (@product.picture.url) %>
          </div>
        <% end %><br>
        <%= form.label :'商品画像'%>
        <%= form.text_field :picture, id: :product_picture%>
        <%= form.file_field :picture, id: :product_picture%>
        <%#= form.hidden_field :picture_cache %>
      </div>

    <div class="field">
      <!-- 既存レコード(DBに保存されている)かつ、画像が存在する場合 画像を削除-->
      <% if @product.persisted? && @product.picture? %>
        <label>
          <%= form.check_box :remove_picture %>
        </label>
      <% end %>
    </div>

    <div class="field">
      <%= form.label :'価格' %>
      <%= form.number_field :price %>
    </div>

    <div class="actions">
      <%= form.submit :'登録する'%>
    </div>
    <% end %>
<% end %>


<!--form_with, form_for , form_tagなどの使い分けが特手のmodelを使うかmethodを推定してくれるかといったところに
あるようですが、いまいちしっくりきていません、、-->

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to '商品詳細', @product %> <!--showへ-->
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p><!--←このidとは？？-->
  <% @products.each do |product| %>
    <p>
      <strong>商品タイトル：</strong>
      <%= @product.item %>
    </p>
    <p>
      <strong>商品説明：</strong>
      <%= @product.content %>
    </p>
    <p>
      <strong>店舗名：</strong>
      <%= @product.shop %>
    </p>
    <p>
      <strong>商品画像：</strong>
      <!--<%= @product.picture %>-->
      <%= image_tag(@product.picture_url) if @product.picture.present? %>
    </p>
    <p>
      <strong>価格：</strong>
      <%= @product.price %>
    </p>
  <% end %>
  


    <br>
    <%= link_to '新規商品登録', new_product_path%>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>
<%= link_to 'Back', products_path %>

app/views/products/search.html.erb
<p id="notice"><%= notice %></p>
<h3>商品検索一覧</h3>
<p>
  <strong>商品検索一覧：</strong>
  <%= @product.item %>
</p>
<table border="1">
<caption>検索結果一覧</caption
  <thead><!--viewについてもう少し学んでこの各項目の間隔をつくりたいです-->
    <tr>
      <th>商品タイトル</th><br>
      <th>商品説明</th><br>
      <th>商品画像名</th><br>
      <th>価格</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.item %></td><br>
        <td><%= product.content %></td><br>
        <td><%= product.picture %></td><br>
        <td><%= product.price %></td><br>
        <td><%= link_to '商品詳細', product %></td> <!--to 商品詳細'show'-->
        <td><%= link_to '変更', edit_product_path(product) %></td><!--to 編集'edit'##(ptoductはなに？)-->
        <td><%= link_to '削除', product, method: :delete, data: { confirm: '一度削除するとデータは完全に失われます。削除してもよいですか？' } %></td>
        <!--to 商品詳細'show'##(method, dataいる？)-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '商品一覧', index_product_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>商品タイトル：</strong>
  <%= @product.item %>
</p>

<p>
  <strong>商品説明：</strong>
  <%= @product.content %>
</p>


<p>
  <strong>店舗名：</strong>
  <%= @product.shop %>
</p>>

<p>
  <strong>商品画像：</strong>
  <!--<%= @product.picture %>-->
  <%= image_tag(@product.picture_url) if @product.picture.present? %>
</p>


<p>
  <strong>価格：</strong>
  <%= @product.price %>
</p>

<%= link_to '変更', edit_product_path(@product) %> |
<%= link_to 'BACK', products_path %>